[theme]
# Primary accent color for interactive elements.
primaryColor = "#E6F06C"

# Background color for the main content area.
backgroundColor = "#621132"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#B8975A"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
